version: "3.8"
services:
  todo-web:
    image: diamol/ch06-todo-list:latest
    ports:
      - "8080:80"
    environment:
      - Database:Provider=Postgres
    env_file:
      - ./logging.information.env
    networks:
      - app-net
  todo-db:
    image: diamol/postgres:11.5
    ports:
      - "5432:5432"
    networks:
      - app-net
networks:
  app-net:
    name: todo-test
secrets:
  todo-db-connection:
    file: ./secrets.json