version: "3.8"
services:
  todo-db:
    image: ${TODO_DB_IMAGE}
    restart: always
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  todo-web:
    image: ${TODO_IMAGE_LATEST}
    ports:
      - "${TODO_PORT_TEST}:80"
    environment:
      - Database:Provider=Postgres
    restart: always
    depends_on:
      - todo-db
    secrets:
      - source: ToDoDb
        target: /app/config/secrets.json

volumes:
  todo-db:
    driver: local

secrets:
  ToDoDb:
    file: ./config/secrets.json