version: "3.8"
services:
  todo-web:
    image: diamol/ch06-todo-list:v2
    ports:
      - "8089:80"
    environment:
      - Database:Provider=Sqlite
    env_file:
      - ./logging.debug.env
secrets:
  todo-db-connection:
    file: ./empty.json
